# Generated by Django 2.0 on 2018-05-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='zip',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
