# Generated by Django 2.0 on 2018-06-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='active',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='trained',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
