# Generated by Django 2.0 on 2018-06-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20180601_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age_range',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
