# Generated by Django 2.0 on 2018-06-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0004_auto_20180602_2210'),
        ('accounts', '0007_auto_20180602_0449'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('accepted', models.NullBooleanField()),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Adopter')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Giver')),
            ],
        ),
        migrations.CreateModel(
            name='MatchSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('accepted', models.NullBooleanField()),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Adopter')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.Shelter')),
            ],
        ),
    ]
