# Generated by Django 2.0 on 2018-05-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopter',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='giver',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
