# Generated by Django 2.0 on 2018-05-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='availability',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='zip_code',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='giver',
            name='zip_code',
            field=models.SmallIntegerField(),
        ),
    ]
